//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinesweeperProjectCLC247.GameAPI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/GameAPI")]
    [System.SerializableAttribute()]
    public partial class DTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MinesweeperProjectCLC247.GameAPI.CellModel[] CellsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClicksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SizeYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double timerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MinesweeperProjectCLC247.GameAPI.CellModel[] Cells {
            get {
                return this.CellsField;
            }
            set {
                if ((object.ReferenceEquals(this.CellsField, value) != true)) {
                    this.CellsField = value;
                    this.RaisePropertyChanged("Cells");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Clicks {
            get {
                return this.ClicksField;
            }
            set {
                if ((this.ClicksField.Equals(value) != true)) {
                    this.ClicksField = value;
                    this.RaisePropertyChanged("Clicks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeX {
            get {
                return this.SizeXField;
            }
            set {
                if ((this.SizeXField.Equals(value) != true)) {
                    this.SizeXField = value;
                    this.RaisePropertyChanged("SizeX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SizeY {
            get {
                return this.SizeYField;
            }
            set {
                if ((this.SizeYField.Equals(value) != true)) {
                    this.SizeYField = value;
                    this.RaisePropertyChanged("SizeY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double timer {
            get {
                return this.timerField;
            }
            set {
                if ((this.timerField.Equals(value) != true)) {
                    this.timerField = value;
                    this.RaisePropertyChanged("timer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CellModel", Namespace="http://schemas.datacontract.org/2004/07/MinesweeperProjectCLC247.Models")]
    [System.SerializableAttribute()]
    public partial class CellModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColumnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsClickedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LiveNeighborsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Column {
            get {
                return this.ColumnField;
            }
            set {
                if ((this.ColumnField.Equals(value) != true)) {
                    this.ColumnField = value;
                    this.RaisePropertyChanged("Column");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageLocation {
            get {
                return this.ImageLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageLocationField, value) != true)) {
                    this.ImageLocationField = value;
                    this.RaisePropertyChanged("ImageLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsClicked {
            get {
                return this.IsClickedField;
            }
            set {
                if ((this.IsClickedField.Equals(value) != true)) {
                    this.IsClickedField = value;
                    this.RaisePropertyChanged("IsClicked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLive {
            get {
                return this.IsLiveField;
            }
            set {
                if ((this.IsLiveField.Equals(value) != true)) {
                    this.IsLiveField = value;
                    this.RaisePropertyChanged("IsLive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisited {
            get {
                return this.IsVisitedField;
            }
            set {
                if ((this.IsVisitedField.Equals(value) != true)) {
                    this.IsVisitedField = value;
                    this.RaisePropertyChanged("IsVisited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LiveNeighbors {
            get {
                return this.LiveNeighborsField;
            }
            set {
                if ((this.LiveNeighborsField.Equals(value) != true)) {
                    this.LiveNeighborsField = value;
                    this.RaisePropertyChanged("LiveNeighbors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/GameAPI")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameAPI.IGameService")]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetGameBoard", ReplyAction="http://tempuri.org/IGameService/GetGameBoardResponse")]
        MinesweeperProjectCLC247.GameAPI.DTO GetGameBoard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetGameBoard", ReplyAction="http://tempuri.org/IGameService/GetGameBoardResponse")]
        System.Threading.Tasks.Task<MinesweeperProjectCLC247.GameAPI.DTO> GetGameBoardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/PutGameBoard", ReplyAction="http://tempuri.org/IGameService/PutGameBoardResponse")]
        bool PutGameBoard();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/PutGameBoard", ReplyAction="http://tempuri.org/IGameService/PutGameBoardResponse")]
        System.Threading.Tasks.Task<bool> PutGameBoardAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetData", ReplyAction="http://tempuri.org/IGameService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetData", ReplyAction="http://tempuri.org/IGameService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGameService/GetDataUsingDataContractResponse")]
        MinesweeperProjectCLC247.GameAPI.CompositeType GetDataUsingDataContract(MinesweeperProjectCLC247.GameAPI.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGameService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MinesweeperProjectCLC247.GameAPI.CompositeType> GetDataUsingDataContractAsync(MinesweeperProjectCLC247.GameAPI.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : MinesweeperProjectCLC247.GameAPI.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.ClientBase<MinesweeperProjectCLC247.GameAPI.IGameService>, MinesweeperProjectCLC247.GameAPI.IGameService {
        
        public GameServiceClient() {
        }
        
        public GameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MinesweeperProjectCLC247.GameAPI.DTO GetGameBoard() {
            return base.Channel.GetGameBoard();
        }
        
        public System.Threading.Tasks.Task<MinesweeperProjectCLC247.GameAPI.DTO> GetGameBoardAsync() {
            return base.Channel.GetGameBoardAsync();
        }
        
        public bool PutGameBoard() {
            return base.Channel.PutGameBoard();
        }
        
        public System.Threading.Tasks.Task<bool> PutGameBoardAsync() {
            return base.Channel.PutGameBoardAsync();
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(string value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MinesweeperProjectCLC247.GameAPI.CompositeType GetDataUsingDataContract(MinesweeperProjectCLC247.GameAPI.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MinesweeperProjectCLC247.GameAPI.CompositeType> GetDataUsingDataContractAsync(MinesweeperProjectCLC247.GameAPI.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
